#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-grpcio_reflection
Version  : 1.46.1
Release  : 21
URL      : https://files.pythonhosted.org/packages/11/84/4728f734230b51ae11db5e672464246aa367d7ba0eab163a4f9224dacc3d/grpcio-reflection-1.46.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/11/84/4728f734230b51ae11db5e672464246aa367d7ba0eab163a4f9224dacc3d/grpcio-reflection-1.46.1.tar.gz
Summary  : Standard Protobuf Reflection Service for gRPC
Group    : Development/Tools
License  : Apache-2.0
Requires: pypi-grpcio_reflection-license = %{version}-%{release}
Requires: pypi-grpcio_reflection-python = %{version}-%{release}
Requires: pypi-grpcio_reflection-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(grpcio)
BuildRequires : pypi(protobuf)

%description
gRPC Python Reflection package
==============================
Reference package for reflection in GRPC Python.

%package license
Summary: license components for the pypi-grpcio_reflection package.
Group: Default

%description license
license components for the pypi-grpcio_reflection package.


%package python
Summary: python components for the pypi-grpcio_reflection package.
Group: Default
Requires: pypi-grpcio_reflection-python3 = %{version}-%{release}

%description python
python components for the pypi-grpcio_reflection package.


%package python3
Summary: python3 components for the pypi-grpcio_reflection package.
Group: Default
Requires: python3-core
Provides: pypi(grpcio_reflection)
Requires: pypi(grpcio)
Requires: pypi(protobuf)

%description python3
python3 components for the pypi-grpcio_reflection package.


%prep
%setup -q -n grpcio-reflection-1.46.1
cd %{_builddir}/grpcio-reflection-1.46.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1652398666
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-grpcio_reflection
cp %{_builddir}/grpcio-reflection-1.46.1/LICENSE %{buildroot}/usr/share/package-licenses/pypi-grpcio_reflection/34ac89724cb7e3fb36bcfe93efabfd012c569a0e
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-grpcio_reflection/34ac89724cb7e3fb36bcfe93efabfd012c569a0e

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
